# Generated by Django 4.2.7 on 2025-10-23 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Reserved"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="available_end_time",
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name="venue",
            name="available_start_time",
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
