# Generated by Django 4.2.7 on 2025-10-23 13:26

from django.db import migrations
from django.utils.text import slugify


DEFAULT_CATEGORIES = [
    "Padel",
    "Tennis",
    "Badminton",
    "Basket",
    "Sepak Bola",
    "Mini Soccer",
    "Futsal",
    "Billiard",
    "Tenis Meja",
    "Volly Ball",
]


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("venues", "Category")
    for name in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(
            name=name,
            defaults={"slug": slugify(name)},
        )


def remove_default_categories(apps, schema_editor):
    Category = apps.get_model("venues", "Category")
    Category.objects.filter(slug__in=[slugify(name) for name in DEFAULT_CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_booking_approved_at_booking_approved_by_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
