# Generated by Django 4.2.7 on 2025-10-25 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_lapangan', '0003_update_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='available_end_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='venue',
            name='available_start_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
