# Generated by Django 5.2.5 on 2025-10-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
