# Generated by Django 5.2.5 on 2025-10-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_payment_deposit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='deposit_amount',
        ),
    ]
