# Generated by Django 5.2.5 on 2025-10-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
                ('nama_lapangan', models.CharField(max_length=200)),
                ('kota', models.CharField(max_length=100)),
                ('lokasi', models.TextField(blank=True, null=True)),
                ('rentang_harga', models.CharField(blank=True, max_length=100, null=True)),
                ('fasilitas', models.TextField(blank=True, null=True)),
                ('image_address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
